import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  ContainerMain: {
    width: "100%",
    height: "100%",
    padding: 20,
  },
  header: {
    width: "100%",
    height: 60,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: "#DFDFDF",
    marginBottom: 20,
  },
  frameProduct: {
    borderBottomWidth: 1,
    borderColor: "#DFDFDF",
    flexDirection: "row",
    paddingTop: 15,
    paddingBottom: 15,
    top: -20,
  },
  imgProduct: {
    width: 60,
    height: 60,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    marginTop: 10,
  },
  frameAllTotal: {
    flexDirection: "row",
    marginTop: 10,
    marginLeft: 100,
    borderRadius: 10,
    width: 98,
    height: 29.65,
    backgroundColor: "#F4F4F4",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#F4F4F4",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  frameCheckBoxAll: {
    flexDirection: "row",
    alignItems: "center",
  },
  txtUpdatePdAll: {
    color: "#646464",
    fontSize: 14,
  },
  btnDelete: {
    width: 71,
    height: 95,
    backgroundColor: "#A42B32",
    justifyContent: "center",
    alignItems: "center",
  },
  imgDelete: {
    position: "relative",
    width: 30,
    height: 30,
  },
  nameProduct: {
    color: "#6D3805",
    fontSize: 18,
    fontWeight: "700",
    paddingLeft: 20,
  },
  nameGram: {
    color: "#6D3805",
    fontSize: 14,
    paddingLeft: 20,
  },
  txtPrice: {
    color: "#6D3805",
    fontSize: 16,
    fontWeight: "400",
    paddingLeft: 15,
    paddingRight: 42,
    paddingTop: 5,
    textAlign: "right",
  },
  btnTru: {
    width: 24.71,
    height: 24.71,
    backgroundColor: "#fff",
    justifyContent: "center",
    borderRadius: 50,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  userHeader: {
    fontSize: 18,
    fontWeight: "bold",
    marginVertical: 10,
  },
  checkBoxAll: {
    width: 15,
    height: 15,
    marginLeft: 10,
  },
  btnCheckout: {
    backgroundColor: "#3CA89F",
    width: 343,
    height: 50,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  frameTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 25,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#DFDFDF",
  },
  txtTotal: {
    color: "#6D3805",
    fontSize: 18,
    fontWeight: "700",
    textAlign: "right",
  },
  txtPriceTotal: {
    color: "#6D3805",
    fontSize: 18,
    fontWeight: "700",
    
  },

  // model
});
